In [2]:
import numpy as np

- create
- basic operations
- math operations
- index and slicing
- boolean filter

In [7]:
a = [1,2,3,4,5,6,7,8,9]
x = np.array(a)
print(x)
print(a)

[1 2 3 4 5 6 7 8 9]
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
arr1 = np.array([10]*10000).reshape(100,100)
print(arr1)

[[10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 ...
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]
 [10 10 10 ... 10 10 10]]


- random
- arange
- linspace

In [12]:
np.random.rand(5,5)

array([[0.97092227, 0.11784412, 0.89760048, 0.98588145, 0.26768587],
       [0.99593627, 0.26314085, 0.66664224, 0.30520455, 0.80321119],
       [0.77162423, 0.66601211, 0.56333164, 0.87293394, 0.33895748],
       [0.10059454, 0.03010027, 0.68698559, 0.70903645, 0.29973008],
       [0.38634376, 0.75195107, 0.62574348, 0.16058412, 0.81631607]])

In [13]:
r1 = np.random.randint(0,9,(10,10))
print(r1)

[[4 8 5 3 5 3 6 8 8 5]
 [2 8 5 4 2 7 4 2 4 6]
 [2 4 1 4 7 7 8 0 5 5]
 [8 4 2 2 3 8 6 0 1 5]
 [3 4 0 3 1 1 0 8 7 4]
 [3 6 8 8 3 1 4 7 2 0]
 [6 8 7 4 3 0 4 6 8 2]
 [7 8 1 6 3 3 4 1 1 2]
 [1 8 2 6 1 7 7 1 4 1]
 [6 8 5 1 6 1 5 4 5 0]]


In [16]:
# start stop gap
np.arange(0,50,.2)

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. , 10.2, 10.4, 10.6, 10.8,
       11. , 11.2, 11.4, 11.6, 11.8, 12. , 12.2, 12.4, 12.6, 12.8, 13. ,
       13.2, 13.4, 13.6, 13.8, 14. , 14.2, 14.4, 14.6, 14.8, 15. , 15.2,
       15.4, 15.6, 15.8, 16. , 16.2, 16.4, 16.6, 16.8, 17. , 17.2, 17.4,
       17.6, 17.8, 18. , 18.2, 18.4, 18.6, 18.8, 19. , 19.2, 19.4, 19.6,
       19.8, 20. , 20.2, 20.4, 20.6, 20.8, 21. , 21.2, 21.4, 21.6, 21.8,
       22. , 22.2, 22.4, 22.6, 22.8, 23. , 23.2, 23.4, 23.6, 23.8, 24. ,
       24.2, 24.4, 24.6, 24.8, 25. , 25.2, 25.4, 25.6, 25.8, 26. , 26.2,
       26.4, 26.6, 26.8, 27. , 27.2, 27.4, 27.6, 27.8, 28. , 28.2, 28.4,
       28.6, 28.8, 29. , 29.2, 29.4, 29.6, 29.8, 30

In [23]:
# start stop number_of_item
np.linspace(1,50,100)

array([ 1.        ,  1.49494949,  1.98989899,  2.48484848,  2.97979798,
        3.47474747,  3.96969697,  4.46464646,  4.95959596,  5.45454545,
        5.94949495,  6.44444444,  6.93939394,  7.43434343,  7.92929293,
        8.42424242,  8.91919192,  9.41414141,  9.90909091, 10.4040404 ,
       10.8989899 , 11.39393939, 11.88888889, 12.38383838, 12.87878788,
       13.37373737, 13.86868687, 14.36363636, 14.85858586, 15.35353535,
       15.84848485, 16.34343434, 16.83838384, 17.33333333, 17.82828283,
       18.32323232, 18.81818182, 19.31313131, 19.80808081, 20.3030303 ,
       20.7979798 , 21.29292929, 21.78787879, 22.28282828, 22.77777778,
       23.27272727, 23.76767677, 24.26262626, 24.75757576, 25.25252525,
       25.74747475, 26.24242424, 26.73737374, 27.23232323, 27.72727273,
       28.22222222, 28.71717172, 29.21212121, 29.70707071, 30.2020202 ,
       30.6969697 , 31.19191919, 31.68686869, 32.18181818, 32.67676768,
       33.17171717, 33.66666667, 34.16161616, 34.65656566, 35.15

# array attribute
- shape
- dtype
- ndim
- size

# basic operations
- sum
- mean
- min
- max
- std
- reshape
- transpose
- flatten

In [24]:
r1.shape

(10, 10)

In [25]:
r1.dtype

dtype('int32')

In [26]:
r1.ndim

2

In [28]:
ar = np.array([15,84,54,6,7,6,4,6])
ar

array([15, 84, 54,  6,  7,  6,  4,  6])

In [29]:
ar.dtype

dtype('int64')

In [36]:
a = np.random.randint(0,9,(5,7))
print(a)
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.mean())
print(a.max())
print(a.min())
print(a.std())
print(a.var())


[[1 8 3 4 4 6 6]
 [6 6 2 6 8 3 2]
 [5 7 6 0 2 0 2]
 [7 5 6 8 8 5 2]
 [2 4 6 6 0 4 1]]
151
[21 30 23 24 22 18 13]
[32 33 22 41 23]
4.314285714285714
8
0
2.446822178972188
5.986938775510205


In [37]:
z = np.random.randint(11,99,(5,5))
print(z)

[[20 61 89 36 15]
 [64 16 82 83 94]
 [59 33 45 50 78]
 [20 84 13 36 15]
 [75 48 66 58 70]]


In [38]:
print(z.T)

[[20 64 59 20 75]
 [61 16 33 84 48]
 [89 82 45 13 66]
 [36 83 50 36 58]
 [15 94 78 15 70]]


In [39]:
print(z.flatten())

[20 61 89 36 15 64 16 82 83 94 59 33 45 50 78 20 84 13 36 15 75 48 66 58
 70]


In [40]:
a = np.random.randint(1,10,(4,5))
print(a)

[[4 4 2 2 4]
 [8 2 1 5 6]
 [3 9 7 4 2]
 [5 4 8 6 9]]


In [41]:
print(a.reshape(10,2))
print(a.reshape(5,2,2))

[[4 4]
 [2 2]
 [4 8]
 [2 1]
 [5 6]
 [3 9]
 [7 4]
 [2 5]
 [4 8]
 [6 9]]
[[[4 4]
  [2 2]]

 [[4 8]
  [2 1]]

 [[5 6]
  [3 9]]

 [[7 4]
  [2 5]]

 [[4 8]
  [6 9]]]


In [42]:
a = np.random.randint(0,9,(2,2))
b = np.random.randint(0,9,(2,2))

In [49]:
print(a)
print(b)
# when using 2 matrix

[[6 2]
 [8 8]]
[[2 1]
 [3 1]]


In [44]:
a+b

array([[ 8,  3],
       [11,  9]], dtype=int32)

In [45]:
a-b

array([[4, 1],
       [5, 7]], dtype=int32)

In [46]:
a/b

array([[3.        , 2.        ],
       [2.66666667, 8.        ]])

In [47]:
a*b

array([[12,  2],
       [24,  8]], dtype=int32)

In [48]:
a@b

array([[18,  8],
       [40, 16]], dtype=int32)

In [50]:
a + 10 # brodcasting

array([[16, 12],
       [18, 18]], dtype=int32)

In [51]:
a + 10 -b

array([[14, 11],
       [15, 17]], dtype=int32)

In [52]:
a / 10 + b * a 

array([[12.6,  2.2],
       [24.8,  8.8]])

In [55]:
# indexing

a[0][0] == a[0,0]

np.True_

In [57]:
mat = np.random.randint(0,9,(5,5))
print(mat)

[[8 5 0 5 5]
 [6 2 3 3 6]
 [6 0 6 3 2]
 [4 0 6 5 8]
 [4 6 8 7 5]]


In [58]:
mat[1:3]

array([[6, 2, 3, 3, 6],
       [6, 0, 6, 3, 2]], dtype=int32)

In [62]:
mat[1:4,1:4]

array([[2, 3, 3],
       [0, 6, 3],
       [0, 6, 5]], dtype=int32)