In [2]:
import numpy as np

In [11]:
arr0=np.zeros(10)
print(arr0)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [12]:
arr1 = np.ones(10)
print(arr1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [22]:
mat = np.arange(9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
